title: Åvägen
resources: !include resources.yaml
views:
  - !include views/diverse_view.yaml
  - !include views/security_view.yaml
  - title: Floorplan
    panel: true
    icon: mdi:floor-plan
    cards:
      - type: vertical-stack
        cards:
        - !include floorplan.yaml
        - !include dev_card.yaml
  - !include views/dev_view.yaml
