homeassistant:
  name: Åvägen

  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  time_zone: !secret timezone_home
  unit_system: metric

  # Everything important is here
  packages: !include_dir_named packages

default_config:
discovery:
frontend:
  themes: !include_dir_merge_named themes
recorder:
  db_url: mysql://hass:hass@db:3306/hass?charset=utf8
logger:
  default: info
  logs:
    homeassistant.components.http.view: warn

http:
  # mydomain.com:443 - proxied by nginx to port 8123
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret proxy_hosts

cloud:
