homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "environment"

    sensor.time:
      <<: *common
    sensor.date:
      <<: *common

sensor:
  - platform: time_date
    display_options:
      - time
      - date
  - platform: rest
    name: week
    resource: https://vecka.nu
    headers:
      Accept: application/json
    value_template: '{{ value_json.week | int }}'

sun:
