homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "logging"

    script.log_message:
      <<: *common
    script.info_message:
      <<: *common
    automation.log_home_assistant_starting:
      <<: *common

script:
  log_message:
    sequence:
      - event: LOG_WRITE
        event_data_template:
          message: "{{ message }}"
  info_message:
    sequence:
      - event: LOG_WRITE
        event_data_template:
          message: "{{ message }}"
          channel: "info"
      - event: LOG_WRITE
        event_data_template:
          message: "INFO: {{ message }}"

automation:
  alias: LOG - Home Assistant Starting
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.info_message
      data:
        message: "Home Assistant started!"
